### ISSUE TITLE
fvm relying on an older version of dart and failing via brew install

### ISSUE THREAD

**Issue by lgleasain** [leoafarias/homebrew-fvm#14]
I'm getting the flowing with the current version of homebrew and no version of dart installed.

It looks like maybe there is a mismatch somewhere?

==> Downloading https://formulae.brew.sh/api/formula.jws.json
#=#=#                                                                          
==> Downloading https://formulae.brew.sh/api/cask.jws.json
#=#=#                                                                          
==> Fetching dependencies for leoafarias/fvm/fvm: dart-lang/dart/dart
==> Fetching dart-lang/dart/dart
==> Downloading https://storage.googleapis.com/dart-archive/channels/stable/rele
Already downloaded: /Users/lgleason/Library/Caches/Homebrew/downloads/d77339c006237e5b869c2c01053747deef26fd77a1302d70cb1d19e2e18e34f6--dartsdk-macos-x64-release.zip
==> Fetching leoafarias/fvm/fvm
==> Downloading https://github.com/leoafarias/fvm/archive/2.4.1.tar.gz
Already downloaded: /Users/lgleason/Library/Caches/Homebrew/downloads/255b443428b6964c7f0983d112bb10f5b25e91e26434a5e2c6ecf241199fd1b0--fvm-2.4.1.tar.gz
==> Installing fvm from leoafarias/fvm
==> Installing dependencies for leoafarias/fvm/fvm: dart-lang/dart/dart
==> Installing leoafarias/fvm/fvm dependency: dart-lang/dart/dart
🍺  /usr/local/Cellar/dart/2.15.1: 868 files, 508.4MB, built in 6 seconds
==> Installing leoafarias/fvm/fvm
==> /usr/local/opt/dart/libexec/bin/dart pub get
Last 15 lines from /Users/lgleason/Library/Logs/Homebrew/fvm/01.dart:
2023-10-18 17:37:03 +0000

/usr/local/opt/dart/libexec/bin/dart
pub
get

Resolving dependencies...
The current Dart SDK version is 2.15.1.

Because fvm requires SDK version >=2.17.0 <3.0.0, version solving failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/leoafarias/homebrew-fvm/issues

**Comment by leoafarias** [comment]
@lgleasain can you install the beta version, this is solved on 3.0, latest version is 3.0.0-beta.5

**Comment by goodwillforyou** [comment]
@leoafarias hi, faced the same problem using the lastest version fvm@3.0.0-beta.5,

(base) ➜  ~ brew tap leoafarias/fvm@3.0.0-beta.5
==> Tapping leoafarias/fvm@3.0.0-beta.5
Cloning into '/usr/local/Homebrew/Library/Taps/leoafarias/homebrew-fvm@3.0.0-beta.5'...
remote: Repository not found.
fatal: repository 'https://github.com/leoafarias/homebrew-fvm@3.0.0-beta.5/' not found
Error: Failure while executing; `git clone https://github.com/leoafarias/homebrew-fvm@3.0.0-beta.5 /usr/local/Homebrew/Library/Taps/leoafarias/homebrew-fvm@3.0.0-beta.5 --origin=origin --template= --config core.fsmonitor=false` exited with 128.
(base) ➜  ~ brew tap leoafarias/fvm             
(base) ➜  ~ brew install fvm@3.0.0-beta.5
==> Downloading https://formulae.brew.sh/api/formula.jws.json
-#O=#     #       #                                                                                                                                                                            
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################################################################################################################################### 100.0%
==> Fetching leoafarias/fvm/fvm@3.0.0-beta.5
==> Downloading https://github.com/leoafarias/fvm/archive/3.0.0-beta.5.tar.gz
==> Downloading from https://codeload.github.com/leoafarias/fvm/tar.gz/refs/tags/3.0.0-beta.5
         -=O=-             #           #           #             #                                                                                                                             
==> Installing fvm@3.0.0-beta.5 from leoafarias/fvm
==> /usr/local/opt/dart/libexec/bin/dart pub get
Last 15 lines from /Users/quanjinfeng/Library/Logs/Homebrew/fvm@3.0.0-beta.5/01.dart:
2023-11-10 08:46:24 +0000

/usr/local/opt/dart/libexec/bin/dart
pub
get

Resolving dependencies...
The current Dart SDK version is 2.14.4.

Because fvm requires SDK version >=2.17.0 <4.0.0, version solving failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/leoafarias/homebrew-fvm/issues

**Comment by leoafarias** [comment]
This has been fixed for the latest version of FVM
