### ISSUE TITLE
brew install fails with this sha256 mismatch over and over again...

### ISSUE THREAD

**Issue by oianmol** [leoafarias/homebrew-fvm#6]
<img width="892" alt="Screenshot 2023-01-30 at 9 19 01 PM" src="https://user-images.githubusercontent.com/4393101/215586064-2259f2ec-d433-468b-a93e-39a4b6131f8d.png">

**Comment by frankylee** [comment]
@oianmol I've had the same issue this morning. Deleting the referenced file in `/Users/Username/Library/Caches/Homebrew/downloads` did not resolve the issue for me. 

However, I was able to look up the `https://github.com/fluttertools/fvm` archive file and manually update the `/opt/homebrew/Library/Taps/leoafarias/homebrew-fvm/fvm.rb` file with the following:

```sh
url "https://github.com/fluttertools/fvm/archive/refs/tags/2.4.1.tar.gz"
sha256 "a79559e6a0a2b0ef9f0ac15223b40b630899422eb65e032ccd194492228197a3"
```

This resolved the issue for me. I hope it works for you, too!

**Comment by horimislime** [comment]
Same here, and the workaround @frankylee mentioned above looks good and solved my issue! I opend PR https://github.com/leoafarias/homebrew-fvm/pull/7 including same fix.

**Comment by leoafarias** [comment]
I went ahead and merged the PR, however this file is created automatically by the FVM deployment script, so I am not sure what might have happened. Will take a look!

**Comment by jmatth** [comment]
> this file is created automatically by the FVM deployment script

Not really, it's generated by Github on-demand whenever someone downloads an archive of the source code. Yesterday they made a change to how that archive is generated which broke this and a bunch of other Homebrew formulas. They've since rolled the change back, which is why the formula [is broken again][2]. [Here's the discussion on the issue][1].

[1]: https://github.com/orgs/community/discussions/45830
[2]: https://github.com/leoafarias/homebrew-fvm/issues/8
